---
# Source: opentelemetry-demo/charts/jaeger/templates/allinone-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  labels:
    helm.sh/chart: jaeger-0.65.1
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.37.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: all-in-one
    helm.sh/release-name: {{ .Release.Name }}
    helm.sh/release-namespace: {{ .Release.Namespace }}
